WITH [STREET_GROUP] AS (
SELECT CASE WHEN [ON_STREET_NAME] LIKE '%STREET' THEN 'STREET'
            WHEN [ON_STREET_NAME] LIKE '%AVENUE' THEN 'AVENUE'  
            WHEN [ON_STREET_NAME] LIKE '%BOULEVARD' THEN 'BOULEVARD' 
            WHEN [ON_STREET_NAME] LIKE '%PLACE' THEN 'PLACE' 
            WHEN [ON_STREET_NAME] LIKE '%ROAD' THEN 'ROAD' 
            WHEN [ON_STREET_NAME] LIKE '%LANE' THEN 'LANE'
            WHEN [ON_STREET_NAME] LIKE '%COURT' THEN 'COURT'
            WHEN [ON_STREET_NAME] LIKE '%TERRACE' THEN 'TERRACE'
            WHEN [ON_STREET_NAME] LIKE '%DRIVE' THEN 'DRIVE'
            WHEN [ON_STREET_NAME] LIKE '%LOOP' THEN 'LOOP'
            WHEN [ON_STREET_NAME] LIKE '%PARKWAY' THEN 'PARKWAY'
            WHEN [ON_STREET_NAME] LIKE '%PKWY' THEN 'PARKWAY'
            WHEN [ON_STREET_NAME] LIKE '%EXPRESSWAY' THEN 'EXPRESSWAY'
            ELSE 'OTHER' END AS [STREET]
  FROM edw.D_LOCATION
)
SELECT [STREET]
     , COUNT(*) AS [STREET_COUNT]
  FROM [STREET_GROUP]
 WHERE [STREET] != 'OTHER'
 GROUP BY [STREET]
 ORDER BY 2 DESC