WITH [VEHICLE] AS (
    SELECT [VEHICLE_TYPE_CODE_1] AS [VEHICLE_TYPE] FROM [car_crash].[edw].[D_VEHICLE]
UNION ALL
    SELECT [VEHICLE_TYPE_CODE_2] AS [VEHICLE_TYPE] FROM [car_crash].[edw].[D_VEHICLE]
UNION ALL
    SELECT [VEHICLE_TYPE_CODE_3] AS [VEHICLE_TYPE] FROM [car_crash].[edw].[D_VEHICLE]
UNION ALL
    SELECT [VEHICLE_TYPE_CODE_4] AS [VEHICLE_TYPE] FROM [car_crash].[edw].[D_VEHICLE]
UNION ALL
    SELECT [VEHICLE_TYPE_CODE_5] AS [VEHICLE_TYPE] FROM [car_crash].[edw].[D_VEHICLE]
)
SELECT [VEHICLE_TYPE]
     , COUNT(*) AS [COUNT]
  FROM [VEHICLE]
 GROUP BY [VEHICLE_TYPE]
 ORDER BY 2 DESC

    